[feat] Add dark mode support
yursan9/manis-hugo-theme pull request #22
Opened 2021-12-18 14:21 UTC by jerrylususu

Hi! I found your great theme, and tried to add a working dark mode support using CSS filters, which uses the system dark mode setting as default value while also remembering users' manual preference. Users can toggle dark mode using the little "sun/moon" icon in the navbar. Previously I am thinking just using the custom CSS support built in the theme, but I feel that this should be a theme-level support for such an essential function.

Most of the code comes from this post: https://radu-matei.com/blog/dark-mode/ , and the moon & sun icon is from [font-awesome](https://fontawesome.com/v5.15/icons). As font-awesome requires credit link to their [license page](https://fontawesome.com/license), there may need some work on `README.md` to include that. 

Still I would like some response, to see if I am working towards the right direction. I am mostly a backend developer and haven't touch frontend code much, so please don't hesitate to provide editing suggestions. 

Here are some screenshots:

Home Page
![image](https://user-images.githubusercontent.com/17522475/146644136-3905d2ab-0789-4daf-b5b1-872b60cb01a5.png)

Article Page (Notice that images are not effected)
![image](https://user-images.githubusercontent.com/17522475/146644181-ced0e06f-b24e-4d4c-8c57-dbaa6183e445.png)

Code highlight & Code block
![image](https://user-images.githubusercontent.com/17522475/146644217-d942444b-6285-4e2f-b8d8-aa03b6c4d5d6.png)

2021-12-22 01:48 UTC, yursan9 requested changes
Thank you for the PR. I'm back-end developer too, that's why the theme is so minimalist. :grin: 
So, for the feature itself, I like it. Regarding the icon I don't mind if you're using from Font Awesome, but for the attribution I need you too add this to the SVG as comment:
```
“Sun Icon” by Font Awesome is licensed under CC BY 4.0. https://fontawesome.com/license/free
“Moon Icon” by Font Awesome is licensed under CC BY 4.0. https://fontawesome.com/license/free
```

2021-12-22 01:50 UTC, yursan9 requested changes

2021-12-22 01:50 UTC, yursan9 commented on static/img/moon.svg
> +<svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="moon" class="svg-inline--fa fa-moon fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="cur
```suggestion
<!-- 
   “Moon Icon” by Font Awesome is licensed under CC BY 4.0. https://fontawesome.com/license/free
-->
<svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="moon" class="svg-inline--fa fa-moon fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M279.135 512c78.756 0 150.982-35.804 198.844-94.775 28.27-34.831-2.558-85.722-46.249-77.401-82.348 15.683-158.272-47.268-158.272-130.792 0-48.424 26.06-92.292 67.434-115.836 38.745-22.05 28.999-80.788-15.022-88.919A257.936 257.936 0 0 0 279.135 0c-141.36 0-256 114.575-256 256 0 141.36 114.576 256 256 256zm0-464c12.985 0 25.689 1.201 38.016 3.478-54.76 31.163-91.693 90.042-91.693 157.554 0 113.848 103.641 199.2 215.252 177.944C402.574 433.964 344.366 464 279.135 464c-114.875 0-208-93.125-208-208s93.125-208 208-208z"></path></svg>
```

2021-12-22 01:50 UTC, yursan9 commented on static/img/sun.svg
> +<svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="sun" class="svg-inline--fa fa-sun fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="curre
```suggestion
<!-- 
   “Sun Icon” by Font Awesome is licensed under CC BY 4.0. https://fontawesome.com/license/free
-->
<svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="sun" class="svg-inline--fa fa-sun fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M494.2 221.9l-59.8-40.5 13.7-71c2.6-13.2-1.6-26.8-11.1-36.4-9.6-9.5-23.2-13.7-36.2-11.1l-70.9 13.7-40.4-59.9c-15.1-22.3-51.9-22.3-67 0l-40.4 59.9-70.8-13.7C98 60.4 84.5 64.5 75 74.1c-9.5 9.6-13.7 23.1-11.1 36.3l13.7 71-59.8 40.5C6.6 229.5 0 242 0 255.5s6.7 26 17.8 33.5l59.8 40.5-13.7 71c-2.6 13.2 1.6 26.8 11.1 36.3 9.5 9.5 22.9 13.7 36.3 11.1l70.8-13.7 40.4 59.9C230 505.3 242.6 512 256 512s26-6.7 33.5-17.8l40.4-59.9 70.9 13.7c13.4 2.7 26.8-1.6 36.3-11.1 9.5-9.5 13.6-23.1 11.1-36.3l-13.7-71 59.8-40.5c11.1-7.5 17.8-20.1 17.8-33.5-.1-13.6-6.7-26.1-17.9-33.7zm-112.9 85.6l17.6 91.2-91-17.6L256 458l-51.9-77-90.9 17.6 17.6-91.2-76.8-52 76.8-52-17.6-91.2 91 17.6L256 53l51.9 76.9 91-17.6-17.6 91.1 76.8 52-76.8 52.1zM256 152c-57.3 0-104 46.7-104 104s46.7 104 104 104 104-46.7 104-104-46.7-104-104-104zm0 160c-30.9 0-56-25.1-56-56s25.1-56 56-56 56 25.1 56 56-25.1 56-56 56z"></path></svg>
```

2021-12-22 06:19 UTC, jerrylususu commented
Hi! Thanks for your reply. I just added the required license comments. Please have a look.

2021-12-26 14:05 UTC, yursan9 approved these changes
LGTM

2021-12-26 14:05 UTC, merged